apiVersion: v1
kind: Service
metadata:
  name: symposium-2018
  namespace: default
  labels:
    app: symposium-2018
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: symposium-2018
  type: ClusterIP
