apiVersion: v1
kind: ConfigMap
metadata:
  name: roundcube
  namespace: default
  labels:
    app: roundcube
data:
  managesieve.config.php: |
    <?php
    $config['managesieve_port'] = 4190;
    $config['managesieve_host'] = 'ch.tudelft.nl';
    $config['managesieve_auth_type'] = null;
    $config['managesieve_auth_cid'] = null;
    $config['managesieve_auth_pw'] = null;
    $config['managesieve_usetls'] = true;
    $config['managesieve_conn_options'] = null;
    $config['managesieve_default'] = null;
    $config['managesieve_script_name'] = null;
    $config['managesieve_mbox_encoding'] = 'UTF-8';
    $config['managesieve_replace_delimiter'] = '';
    $config['managesieve_disabled_extensions'] = array();
    $config['managesieve_debug'] = false;
    $config['managesieve_kolab_master'] = false;
    $config['managesieve_filename_extension'] = '.sieve';
    $config['managesieve_filename_exceptions'] = array();
    $config['managesieve_domains'] = array();
    $config['managesieve_vacation'] = 0;
    $config['managesieve_vacation_interval'] = 0;
    $config['managesieve_vacation_addresses_init'] = false;
    $config['managesieve_notify_methods'] = array('mailto');
  nginx.conf: |
    server {
        listen 80;
        charset utf-8;
        client_max_body_size 10M;

        location /mail {
            alias /var/www/html;
            index index.php;
            try_files $uri $uri/ index.php;

            location ~ /\.ht {
                deny all;
                access_log off;
                log_not_found off;
            }

            location ~* \.php$ {
                try_files $uri =404;
                include /etc/nginx/fastcgi_params;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass localhost:9000;
                fastcgi_param SCRIPT_FILENAME $request_filename;
                fastcgi_index index.php;
            }
        }
    }
