apiVersion: v1
kind: Service
metadata:
  name: roundcube
  namespace: default
  labels:
    app: roundcube
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: roundcube
  sessionAffinity: None
  type: ClusterIP
