apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackdelft-2019
  namespace: hackdelft
  labels:
    app: hackdelft-2019
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hackdelft-2019
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: hackdelft-2019
      labels:
        app: hackdelft-2019
    spec:
      containers:
      - name: hackdelft-2019
        image: quay.io/wisvch/hackdelft-2019:61
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - name: tmpfs
          mountPath: /tmp
      volumes:
      - name: tmpfs
        emptyDir:
          medium: Memory

