apiVersion: v1
kind: Service
metadata:
  labels:
    app: hackdelft-2019
  name: hackdelft-2019
  namespace: hackdelft
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: hackdelft-2019
  sessionAffinity: None
  type: ClusterIP
