apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bapc
  namespace: default
spec:
  rules:
    - host: bapc.eu
      http:
        paths:
        - backend:
            serviceName: bapc-2020
            servicePort: 80
          path: /2020
  tls:
    - hosts:
        - bapc.eu
      secretName: ingress-ext-tls
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/temporal-redirect: https://2020.bapc.eu
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: bapc-redirect
  namespace: default
spec:
  rules:
    - host: bapc.eu
      http:
        paths:
          - path: /$
            backend:
              serviceName: bapc.eu
              servicePort: 80
  tls:
    - hosts:
        - bapc.eu
      secretName: ingress-ext-tls
