apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bapc
  namespace: default
spec:
  rules:
    - host: commissies.ch.tudelft.nl
      http:
        paths:
        - backend:
            serviceName: bapc-2020
            servicePort: 80
          path: /bapc-2020
  tls:
    - hosts:
        - commissies.ch.tudelft.nl
      secretName: ingress-ext-tls