apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: default
  labels:
    app: payments
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: payments
  sessionAffinity: None
  type: ClusterIP
