apiVersion: v1
kind: Service
metadata:
  name: lancie-frontend-beta
  namespace: lancie
  labels:
    app: lancie-frontend-beta
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: lancie-frontend-beta
  sessionAffinity: None
  type: ClusterIP
