apiVersion: v1
kind: Service
metadata:
  name: wiki
  namespace: default
  labels:
    app: wiki
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: wiki
  sessionAffinity: None
  type: ClusterIP
