---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homedirs
  namespace: default
  labels:
    app: homedirs
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: homedirs
  strategy:
    type: Recreate
  template:
    metadata:
      name: homedirs
      labels:
        app: homedirs
    spec:
      containers:
      - name: homedirs
        image: quay.io/wisvch/homedirs:sha-25f2293
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
        volumeMounts:
        - name: homedirs
          mountPath: /data
          readOnly: true
      volumes:
      - name: homedirs
        persistentVolumeClaim:
          claimName: homedirs
