---
# Manually create PersistentVoume to bind existing VMDK
# docs: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homedirs
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 700Gi
  claimRef:
    name: homedirs
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vsphere
  volumeMode: Filesystem
  vsphereVolume:
    fsType: xfs
    volumePath: '[datastore1] kubevols/homedirs.vmdk'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homedirs
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 700Gi
  storageClassName: vsphere
