apiVersion: v1
kind: Service
metadata:
  labels:
    app: homedirs
  name: homedirs
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: homedirs
  type: ClusterIP
