apiVersion: v1
kind: Service
metadata:
  name: hackdelft-2018
  namespace: hackdelft
  labels:
    app: hackdelft-2018
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: hackdelft-2018
  sessionAffinity: None
  type: ClusterIP
