apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: connect
  namespace: default
spec:
  rules:
  - host: connect.ch.tudelft.nl
    http:
      paths:
      - backend:
          serviceName: connect
          servicePort: 80
  tls:
  - hosts:
    - connect.ch.tudelft.nl
    secretName: ingress-ext-tls
