apiVersion: v1
kind: Service
metadata:
  name: lancie-api
  namespace: lancie
  labels:
    app: lancie-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: lancie-api
  sessionAffinity: None
  type: ClusterIP
