apiVersion: v1
kind: Service
metadata:
  name: lancie-admin
  namespace: lancie
  labels:
    app: lancie-admin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: lancie-admin
  sessionAffinity: None
  type: ClusterIP
