apiVersion: v1
kind: Service
metadata:
  labels:
    app: modify-password
  name: modify-password
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: modify-password
  type: ClusterIP
