apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: w3cie
  labels:
    app: website
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: website
  sessionAffinity: None
  type: ClusterIP
