apiVersion: v1
kind: Service
metadata:
  labels:
    app: bapc-2020
  name: bapc-2020
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: bapc-2020
  type: ClusterIP
