apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: bapc-2020
  name: chtv
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bapc-2020
  type: ClusterIP
