apiVersion: v1
kind: Service
metadata:
  labels:
    app: symposium-2017
  name: symposium-2017
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: symposium-2017
  sessionAffinity: None
  type: ClusterIP
