---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hendrik
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hendrik
  namespace: default
rules:
  # Allow SA for hendrik.chnet to get ingress-ext-tls secret
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["ingress-ext-tls"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hendrik
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hendrik
subjects:
- kind: ServiceAccount
  name: hendrik
  namespace: default
